# Лабораториска вежба бр. 1

## Вовед

Множење на вектори и матрици

In [1]:
import numpy as np

x = np.array([1, 2, 3])
A = np.array([[2, 4, 6], [1, 0, 1]])
B = np.array([[1, 4, 3, 2, 0], [0, -4, 2, 1, 4], [5, 1, 2, -7, 3]])

print(A @ x)                        # Множење на матрица со вектор
print(np.matmul(A, x), end='\n\n')  # Еквивалентно со претходното

print(A @ B, end='\n\n')            # Множење на матрици

# print (B @ A, end='\n\n')         # Грешка - треба да се внимава на димензиите на матриците при нивно множење

print(B.T @ A.T)                    # Транспонирање на `numpy` матрици и нивно множење

[28  4]
[28  4]

[[ 32  -2  26 -34  34]
 [  6   5   5  -5   3]]

[[ 32   6]
 [ -2   5]
 [ 26   5]
 [-34  -5]
 [ 34   3]]


Решавање системи линеарни равенки

In [3]:
import numpy.linalg             # Ќе го користиме модулот `linalg` од `numpy`

A = np.array([[1, 0, 0], [0, 1, 1], [0, 0, 1]])
b = np.array([1, 2, 1])

print(np.linalg.solve(A, b))    # Функцијата `solve` дава решение на матричната равенка `Ax = b`
                                # Мора да бидат задоволени следните услови:
                                # 1) A е квадратна матрица
                                # 2) Матрицата е несингуларна - има единствено решение за равенката `Ax = b`
                                # т.е. сите редици/колони се линеарно независни.

x = np.linalg.solve(A, b)
a = [1, 1, 1]
print(np.allclose(x, a))        # Проверка дали `x` и `a` се приближно еднакви (до одредено ниво на толеранција)

[1. 1. 1.]
True


## Основен дел

Да се реши системот равенки:
$$\begin{align*} 
&x_1 &&+4x_2 &&+ 3x_3 &&+ 4x_4 &&=& 3 \\ 
&    &&+2x_2 &&+x_3 &&+ 4x_4 &&=& 12 \\ 
&x_1 &&+x_2 &&-5x_3 &&-2 x_4 &&=& 7 \\ 
&    &&  &&-2x_3 &&+ 3x_4 &&= &1  \end{align*}$$

In [5]:
A = np.array([[1,4,3,4], [0,2,1,4], [1,1,-5,-2], [0,0,-2,3]])
b = np.array([3,12,7,1])
print(np.linalg.solve(A,b))

[-25.30769231  11.53846154  -3.38461538  -1.92307692]


Да се провери дали $(-1, -2, 1, 0)$, $(2, 4, -2, 1)$ и $(7, 14, -7, 0)$ се решенија на системот равенки: 
$$\begin{align*} 
&x && +y &&+ 3z &&+t &&=& 0 \\ 
& x   &&-y &&-z &&-t &&=& 0 \\ 
&3x &&+y &&+5z &&+3t &&=& 0 \\ 
&  x  && +5y &&+11z &&+8t &&= &0  \end{align*}$$

In [19]:
A = np.array([[1,1,3,1], [1,-1,-1,-1], [3,1,5,3], [1,5,11,8]])
x1 = np.array([-1,-2,1,0])
x2 = np.array([2,4,-2,1])
x3 = np.array([7,14,-7,0])
solutions = [x1,x2,x3]
for solution in solutions:
    if tuple(A @ solution) == (0, 0, 0, 0,):
        print(solution, "is a solution to A")

[-1 -2  1  0] is a solution to A
[ 7 14 -7  0] is a solution to A


Да се најде решение на векторските равенки
$x_1 \begin{pmatrix}6 \\ 1 \\ 3\end{pmatrix} + x_2 \begin{pmatrix}4\\ 5 \\ 2\end{pmatrix} = \begin{pmatrix}0 \\ -1 \\ 0\end{pmatrix}$

In [43]:
A = np.array([[6,4], [1,5]])
b = np.array([0,-1])
x = np.linalg.solve(A,b)
print("Solution is: [x1, x2] = ",x)
print("To check if this vector is the solution, we multiply it by A. If we get b -> x is a solution to equation.")
if tuple(A@x) == tuple(b):
    print("x is a solution to the equation")
else:
    print("x is NOT a solution the equation")


Solution is: [x1, x2] =  [ 0.15384615 -0.23076923]
To check if this vector is the solution, we multiply it by A. If we get b -> x is a solution to equation.
x is a solution to the equation


Провери дали векторот $x = \begin{pmatrix}1\\ 0\\ -3\end{pmatrix}$ се наоѓа во спанот на векторите $u = \begin{pmatrix}4\\ 12\\ -7\end{pmatrix}$, $v = \begin{pmatrix}-5\\ 2\\ 0\end{pmatrix}$ и $w = \begin{pmatrix}-1\\ 100\\ 0\end{pmatrix}$.

In [37]:
A = np.array([[4,-5, -1], [12,2,100], [-7, 0, 0]])
b = np.array([1,0,-3])
print("Solution is: [c1, c2, c3] = ",np.linalg.solve(A,b))
print("Since there exist c1,c2 and c3 -> x is a linear combination of u,v and w")

Solution is: [c1, c2, c3] =  [ 0.42857143  0.15375789 -0.05450373]
Since there exist c1,c2 and c3 -> x is a linear combination of u,v and w


Определи ги коефициентите на полиномот $f(x) = x^2 + ax + b$, ако е дадено дека $f(1) = 5$ и $f(10) = 12$

In [41]:
A = np.array([[1,1], [10,1]])
b = np.array([4, -88])
print("a, b = ",np.linalg.solve(A,b))

a, b =  [-10.22222222  14.22222222]


## Практичен дел

Колкава пропорција од шпагети, пилешко и зелена салата треба да се земе за да се подготви јадење кое ќе се состои од 600 калории, $45g$ протеини и $15g$ растителни влакна?

Податоци за хранливи состојки при порција храна

\begin{align*}
\textbf{Хран. сост.} && \textbf{Шпагети} && \textbf{Пилешко} && \textbf{Зелена салата} \\
Калории && 270 && 70 && 51 \\
Протеини (g) && 10 && 15 && 5.4 \\
Раст. влакна (g) && 2 && 0 && 5.2 
\end{align*}

In [49]:
A = np.array([[270,70, 51], [10,15,5.4], [2,0,5.2]])
b = np.array([600, 45, 15])
print("The proportions are (for spagetti, chicken, green salad):",np.linalg.solve(A,b))

The proportions are (for spagetti, chicken, green salad): =  [1.47873363 1.18046378 2.31587168]


Да се балансира равенката со цел хемиската реакција да биде можна:
$$NaHCO_3 + H_3 C_6 H_5 O_7 \to Na_3 C_6 H_5 O_7 + H_2 O + CO_2$$

In [51]:
A = np.array([[1,0,-3,0,0], [1,8,-5,-2,0], [1,6,-6,0,-1], [3,7,-7,-1,-2], [1,1,1,1,1]])
b = np.array([0,0,0,0,11])
# we see each coef like an element from the vector x that we want to find, and we see each chem. formula like a colum from the matrix A, where the rows are Na, H, C, O
print("Coef. are = ",np.linalg.solve(A,b))

Coef. are =  [3. 1. 1. 3. 3.]


Дадена е тенка триаголна плоча со рамномерна густина и дебелина со точки во координатите $x = (0, 1)$, $y = (8, 1)$ и $v_3=(2, 4)$.

а) Да се најде рамнотежната точка на плочата.

б) Сакаме плочката да има рамнотежна точка во координатите $(2, 2)$. Како треба да ја прераспределиме густината на плочката во точките $x, y$ и $z$ за да плочката има рамнотежна точка во $(2, 2)$?

In [59]:
# a
x = np.array([0,1])
y = np.array([8,1])
z = np.array([2,4])
tezhina = (x + y + z) / 3
print("Tezhinata e ", tezhina)

# 
A = np.array([[0,8,2], [1,1,4], [1,1,1]])
b = np.array([6,6,1])
print(np.linalg.solve(A,b))

Tezhinata e  [3.33333333 2.        ]
[-1.          0.33333333  1.66666667]
