# Лабораториска вежба бр. 1

## Вовед

Множење на вектори и матрици

In [1]:
import numpy as np

x = np.array([1, 2, 3])
A = np.array([[2, 4, 6], [1, 0, 1]])
B = np.array([[1, 4, 3, 2, 0], [0, -4, 2, 1, 4], [5, 1, 2, -7, 3]])

print(A @ x)                        # Множење на матрица со вектор
print(np.matmul(A, x), end='\n\n')  # Еквивалентно со претходното

print(A @ B, end='\n\n')            # Множење на матрици

# print (B @ A, end='\n\n')         # Грешка - треба да се внимава на димензиите на матриците при нивно множење

print(B.T @ A.T)                    # Транспонирање на `numpy` матрици и нивно множење

[28  4]
[28  4]

[[ 32  -2  26 -34  34]
 [  6   5   5  -5   3]]

[[ 32   6]
 [ -2   5]
 [ 26   5]
 [-34  -5]
 [ 34   3]]


Решавање системи линеарни равенки

In [2]:
import numpy.linalg             # Ќе го користиме модулот `linalg` од `numpy`

A = np.array([[1, 0, 0], [0, 1, 1], [0, 0, 1]])
b = np.array([1, 2, 1])

print(np.linalg.solve(A, b))    # Функцијата `solve` дава решение на матричната равенка `Ax = b`
                                # Мора да бидат задоволени следните услови:
                                # 1) A е квадратна матрица
                                # 2) Матрицата е несингуларна - има единствено решение за равенката `Ax = b`
                                # т.е. сите редици/колони се линеарно независни.

x = np.linalg.solve(A, b)
a = [1, 1, 1]
print(np.allclose(x, a))        # Проверка дали `x` и `a` се приближно еднакви (до одредено ниво на толеранција)

[1. 1. 1.]
True


## Основен дел

Да се реши системот равенки:
$$\begin{align*} 
&x_1 &&+4x_2 &&+ 3x_3 &&+ 4x_4 &&=& 3 \\ 
&    &&+2x_2 &&+x_3 &&+ 4x_4 &&=& 12 \\ 
&x_1 &&+x_2 &&-5x_3 &&-2 x_4 &&=& 7 \\ 
&    &&  &&-2x_3 &&+ 3x_4 &&= &1  \end{align*}$$

Да се провери дали $(-1, -2, 1, 0)$, $(2, 4, -2, 1)$ и $(7, 14, -7, 0)$ се решенија на системот равенки: 
$$\begin{align*} 
&x && +y &&+ 3z &&+t &&=& 0 \\ 
& x   &&-y &&-z &&-t &&=& 0 \\ 
&3x &&+y &&+5z &&+3t &&=& 0 \\ 
&  x  && +5y &&+11z &&+8t &&= &0  \end{align*}$$

Определи ги коефициентите на полиномот $f(x) = x^2 + ax + b$, ако е дадено дека $f(1) = 5$ и $f(10) = 12$

Да се најде решение на векторскaтa равенкa
$x_1 \begin{pmatrix}6 \\ 1 \\ 3\end{pmatrix} + x_2 \begin{pmatrix}4\\ 5 \\ 2\end{pmatrix} = \begin{pmatrix}0 \\ -1 \\ 0\end{pmatrix}$

Провери дали векторот $x = \begin{pmatrix}1\\ 0\\ -3\end{pmatrix}$ се наоѓа во спанот на векторите $u = \begin{pmatrix}4\\ 12\\ -7\end{pmatrix}$, $v = \begin{pmatrix}-5\\ 2\\ 0\end{pmatrix}$ и $w = \begin{pmatrix}-1\\ 100\\ 0\end{pmatrix}$.

За матрица $А=\begin{pmatrix}2&2&1&0&7\\4&0&0&0&1\\3&0&1&-2&2\\4&-5&-4&3&3\end{pmatrix}$, да се искористат најмногу колони од $A$ за да се конструира матрица $B$ таква што равенката $Bx = 0$ ќе го има само тривијалното решение.

## Практичен дел

Во експеримент за јакост на материјали, беше измеренa затезната напнатост на метална прачка при различни нивоа на напрегање:

$$\begin{align*} 
\text{Напрегање (0.1 \%):} &&0 &&2 &&4 &&6 &&8 &&10 \\ 
\text{Напнатост (MPa):} &&0 &&12.5 &&65.2 &&145.9 &&237.6 &&355.0
\end{align*}$$

Најдете интерполирачки полином за овие податоци и проценете ја напнатоста на прачката кога напрегањето на материјалот ќе достигне $7.5\%.$

Дадена е тенка триаголна плоча со рамномерна густина и дебелина со точки во координатите $x = (0, 1)$, $y = (8, 1)$ и $v_3=(2, 4)$.

а) Да се најде рамнотежната точка на плочата.

б) Сакаме плочката да има рамнотежна точка во координатите $(2, 2)$. Како треба да ја прераспределиме густината на плочката во точките $x, y$ и $z$ за да плочката има рамнотежна точка во $(2, 2)$?

Да се балансира равенката со цел хемиската реакција да биде можна:
$$NaHCO_3 + H_3 C_6 H_5 O_7 \to Na_3 C_6 H_5 O_7 + H_2 O + CO_2$$

Колкава пропорција од шпагети, пилешко и зелена салата треба да се земе за да се подготви јадење кое ќе се состои од 600 калории, $45g$ протеини и $15g$ растителни влакна?

Податоци за хранливи состојки при порција храна

\begin{align*}
\textbf{Хран. сост.} && \textbf{Шпагети} && \textbf{Пилешко} && \textbf{Зелена салата} \\
Калории && 270 && 70 && 51 \\
Протеини (g) && 10 && 15 && 5.4 \\
Раст. влакна (g) && 2 && 0 && 5.2 
\end{align*}