# Лабораториска вежба бр. 5

## Вовед

**Сопствени вектори** и **сопствени вредности** (анг. *eigenvectors*, *eigenvalues*) се термини кои опишуваат одредени својства кај квадратните матрици.

Нека $A$ е квадратна матрица и нека важи равенството
$$A \mathbf{v} = \lambda \mathbf{v}$$
за некој вектор $\mathbf{v}$ и некој скалар $\lambda$.  
Векторот $\mathbf{v}$ се нарекува сопствен вектор на матрицата $A$, и тој соодветствува на сопствената вредност $\lambda$.

За пресметка на сопствените вектори и сопствените вредности во `numpy` ќе ја користиме функцијата `numpy.linalg.eig`.

In [1]:
import numpy as np

A = np.array([[1, 2], [2, 8]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print(eigenvalues, end='\n\n')
print(eigenvectors, end='\n\n')

# Внимавај на индексирањето
print('Сопствената вредност: ', eigenvalues[1])
print(' одговара на сопствениот вектор: ', eigenvectors[:, 1])

[0.46887113 8.53112887]

[[-0.96649965 -0.25666794]
 [ 0.25666794 -0.96649965]]

Сопствената вредност:  8.531128874149275
 одговара на сопствениот вектор:  [-0.25666794 -0.96649965]


Сопствените вектори пред и по трансформација го имаат истиот правец, па така матрицата $A$ во равенката
$$A \mathbf{v} = \lambda \mathbf{v}$$
ја интерпретираме како скалирачка функција за сопствените вектори.

b-eigenvector.svg

На примерот на сликата гледаме како само векторите кои лежат на оската на ротација (сино) нема да се ротираат, туку само ќе се скалираат ($\lambda = 1$).

Сопствените вредности може да бидат и комплексни броеви. Во поголемиот дел од вежбите ќе работиме само со реални сопствени вредности. Поради можни грешки во пресметковната прецизност од страна на `numpy`, некогаш ќе биде потребно да ги кастираме вредностите во реални броеви.

In [3]:
eigenvalues = np.real(eigenvalues)
eigenvectors = np.real(eigenvectors)

**Дијагонализација** на квадратната матрица $A$ е претворање на истата (ако е можно) во форма $PDP^{-1}$ каде $P$ ги содржи сопствените вектори, а $D$ е дијагонална матрица од сопствените вредности.

In [8]:
A = np.random.random((4, 4))
A = (A + A.T) / 2  # Симетрични матрици секогаш може да се дијагонализираат

eigenvalues, eigenvectors = np.linalg.eig(A)

P = eigenvectors
D = np.diag(eigenvalues)

P_inv = np.linalg.inv(P)
B = P @ D @ P_inv

# Двете матрици треба да се идентични
print(A, end='\n\n')
print(B)


[[0.51576346 0.31560318 0.77950172 0.64033738]
 [0.31560318 0.86487849 0.74234423 0.38692215]
 [0.77950172 0.74234423 0.13116846 0.4866655 ]
 [0.64033738 0.38692215 0.4866655  0.29946972]]

[[0.51576346 0.31560318 0.77950172 0.64033738]
 [0.31560318 0.86487849 0.74234423 0.38692215]
 [0.77950172 0.74234423 0.13116846 0.4866655 ]
 [0.64033738 0.38692215 0.4866655  0.29946972]]


## Основен дел

Да се пресметаат сопствените вектори и сопствените вредности на матрицата
$$A = \begin{bmatrix}1 & 3 \\ 2 & 0\end{bmatrix}.$$

In [2]:
A = np.array([[1, 3], [2, 0]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print(eigenvalues, end='\n\n')
print(eigenvectors, end='\n\n')

[ 3. -2.]

[[ 0.83205029 -0.70710678]
 [ 0.5547002   0.70710678]]



Да се пресметаат сопствените вектори и сопствените вредности за матрицата
$$A = \begin{bmatrix}-2 & 0 & 0 \\ 0 & -3 & 0 \\ 0 & 0 & 2\end{bmatrix}.$$

Што забележуваш за сопствените вредности?

In [9]:
A = np.array([[-2, 0, 0], [0, -3, 0], [0, 0, 2]])
eigenValues, eigenVectors, = np.linalg.eig(A)
print(eigenValues)
print(eigenVectors)

[-2. -3.  2.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


EigenValues are the same with the non 0 entries in each row in the matrix A

Дадена е сингуларната матрица $$A = \begin{bmatrix}1 & 2 \\ 3 & 6\end{bmatrix},$$
т.е. $det(A) = 0$.

Да се пресметаат сопствените вредности и да се утврди дека 0 е една од сопствените вредности.



In [11]:
A = np.array([[1, 2], [3, 6]])
eigenValues, eigenVectors, = np.linalg.eig(A)
print(eigenValues)
print(eigenVectors)
for value in eigenValues:
    if value == 0:
        print("There is an eigenvalue == 0")

[0. 7.]
[[-0.89442719 -0.31622777]
 [ 0.4472136  -0.9486833 ]]
There is an eigenvalue == 0


Дадена е сингуларната матрица $$A = \begin{bmatrix}2 & 2 & -2 \\ 5 & 1 & -3 \\ 1 & 5 & -3\end{bmatrix}.$$

а) Утврди дека сите сопствени вредности на матрицата се 0.

б) Ваквиот тип на матрици $N$ со сопствени вредности нула (анг. *Nilpotent*) го имаат следното својство: $$N^k = \mathbf{0}$$ за некој позитивен цел број $k$. Најди го најмалиот таков број за матрицата $A$.

In [21]:
A = np.array([[2, 2, -2], [5, 1, -3], [1, 5, -3]])
eigenValues, eigenVectors, = np.linalg.eig(A)
roundedEigenValues = (np.round(np.real(eigenValues)))
# print(roundedEigenValues)
if len(list(filter(lambda x: x == 0, roundedEigenValues))) == len(roundedEigenValues):
    print("All the eigenValues are 0")
    print("Proof,", roundedEigenValues)

All the eigenValues are 0
Proof, [-0.  0.  0.]


In [30]:
k = 1
zeroMatrix  =np.zeros((3, 3))
while True:
    matrixProduct = A
    for i in range(2,k+1):
        matrixProduct = matrixProduct @ A
    if np.array_equal(matrixProduct, zeroMatrix):
        break
    k += 1
    
print("For k =",k,f", A^{k} = 0")

For k = 3 , A^3 = 0


За произволна матрица $A$, провери дека скалиран сопствен вектор за сопствената вредност $\lambda$ е исто така сопствен вектор.

Односно покажи дека ако важи
$$A\mathbf{v} = \lambda \mathbf{v},$$
тогаш исто важи и
$$A(k\mathbf{v}) = \lambda k \mathbf{v}$$
за произволен скалар $k$.

In [46]:
A = np.array([[-2, 0, 0], [0, -3, 0], [0, 0, 2]])
eigenValues, eigenVectors, = np.linalg.eig(A)
# print(eigenValues)
# print(eigenVectors)

eigen_vector= eigenVectors[0]
print("For A =\n", A,"\nand eigenvector v = ",eigen_vector)
print("Av = ", A @ eigen_vector,",where lamda=", eigenValues[0])
k1 = 3
scaled_eigen_vector = k1 * eigen_vector
print("If we scale v with k = 3 -> v =", scaled_eigen_vector)
print("Then, A(kv) = ", A @ (k * eigen_vector), "which is the same with lamda*kv=", eigenValues[0] * k * eigen_vector)

For A =
 [[-2  0  0]
 [ 0 -3  0]
 [ 0  0  2]] 
and eigenvector v =  [1. 0. 0.]
Av =  [-2.  0.  0.] ,where lamda= -2.0
If we scale v with k = 3 -> v = [3. 0. 0.]
Then, A(kv) =  [-6.  0.  0.] which is the same with lamda*kv= [-6. -0. -0.]


Дефинирајте матрица на ротација $R$ во 2D простор.

а) Пред да ги пресметате сопствените вредности и сопствените вектори, размислете како изгледа трансформацијата за аглите $\alpha = 90^{\circ}$ и $\alpha = 180^{\circ}$.

Кои сопствени вредности ги очекуваме да се добијат?

б) Пресметај ги сопствените вредности.

In [51]:
def get_rotation_matrix(theta):
    theta_rad = np.radians(theta)
    return np.array([
        [np.cos(theta_rad), -np.sin(theta_rad)],
        [np.sin(theta_rad), np.cos(theta_rad)]
    ])

In [59]:
rotation_by_90 = np.round(get_rotation_matrix(90))
rotation_by_180 = np.round(get_rotation_matrix(180))
print("Rotation by 90\n",rotation_by_90)
print("Rotation by 180\n",rotation_by_180)

Rotation by 90
 [[ 0. -1.]
 [ 1.  0.]]
Rotation by 180
 [[-1. -0.]
 [ 0. -1.]]


In [61]:
eigValues90, eigVectors90 = np.linalg.eig(rotation_by_90)
eigValues180, eigVectors180 = np.linalg.eig(rotation_by_180)

We expect to get the eigenvalues 0,0 for rotation by 90, and eigenvalues -1,-1 for rotation by 180

In [66]:
print("Eigen values for rotation by 90",np.real(eigValues90))

Eigen values for rotation by 90 [0. 0.]


In [65]:
print("Eigen values for rotation by 90",np.real(eigValues180))

Eigen values for rotation by 90 [-1. -1.]


Направи дијагонализација на матрицата
$$A = \begin{bmatrix}5 & 2 \\ 2 & 8\end{bmatrix}.$$

Дали е важен редоследот на множењето на матриците, т.е. дали $PDP^{-1}$ е исто со $P^{-1}DP$?

In [75]:
A = np.array([[5,2],[2,8]])
eigenvalues, eigenvectors = np.linalg.eig(A)
P = eigenvectors
D = np.diag(eigenvalues)

P_inv = np.linalg.inv(P)
Result = P @ D @ P_inv
Result_1 = np.round(P @ P_inv @ D)

print("A=\n",A, end='\n\n')
print("PDP-1=\n",Result)
print("PP-1D=\n",Result_1)
print()
if np.array_equal(Result,Result_1):
    print("PDP-1 = PP-1D")
else:
    print("PDP-1 != PP-1D")
    

A=
 [[5 2]
 [2 8]]

PDP-1=
 [[5. 2.]
 [2. 8.]]
PP-1D=
 [[ 4.  0.]
 [-0.  9.]]

PDP-1 != PP-1D


Во кодот што следи е дадена матрица $A$ од случајни вредности од ред $1000 \times 1000$ која потоа е трансформирана во симетрична матрица (па може да се дијагонализира).

а) Да се направи дијагонализација на матрицата.

б) Со помош на $P$ и $Q$ матриците да се изрази $A^2$ и $A^3$ на лист хартија. Што забележуваш?

в) Напиши две функции кои ќе ја пресметаат вредноста на $A^{100}$.

Првата функција ќе прави наивно матрично множење на матрицата 100 пати, т.е. $$result = \underbrace{A A \cdots A}_{\text{100 пати}}.$$

Втората функција прво ќе ја дијагонализира матрицата, па користејќи го трикот од б) ќе го пресмета 100-тиот степен на матрицата.

Пред извршувањето на секоја од функциите може да го измерите времето потребно за да заврши пресметката на степенот на матрицата. Од модулот `time` користете ја исто-именуваната функција `time` на следниот начин: `start_time = time()`.

## Практичен дел

Следниот тип на анализа се применува за проучување на популацијата на стадо бизони. Популацијата на бизони ќе ја поделиме во три групи: малолетници кои имаат помалку од една година; годишници од една до две години; и возрасни кои се постари од две години.

Секоја година  
- 80% од малолетниците преживуваат и стануваат годишници;  
- 90% до годишниците преживуваат и стануваат возрасни;  
- 80% од возрасните преживуваат;
- 40% од возрасните раѓаат малолетник.

Дефинирај ја матрицата $A$ од веројатности бизон од еден тип да премине во друг тип.

а) Нека $x$ е вектор од некоја почетна популација што ќе ја дефинирате вие. Што се случува со популацијата по неколку години?

б) Промени ја веројатноста за возрасните да раѓаат малолетници на 30% и 20%. Како се однесуваат овие промени врз развојот на стадото низ времето?

In [1]:
P = np.array([
    [0.2, 0.8, 0],
    [0, 0.1, 0.9],
    [0.4, 0, 0.8]
])

x = np.array([100, 50, 200])

years = 5
populations = [x]
for t in range(years):
    vt = P @ populations[-1]
    populations.append(vt)

# Convert to numpy array for easier slicing
populations = np.array(populations)
print(populations)  #So vreme se zgolemuva



NameError: name 'np' is not defined

**Principal Component Analysis** (PCA) е техника за редукција на димензионалност кога податочните множества изобилуваат со голем број на атрибути.

Дефинирајте податочно множество од 2D точки (барем 4 точки). Секоја редица се однесува на една точка, додека првата колона се х-вредностите на тие точки (аналогно со втората колона за у-вредностите).

Пресметај ја коваријансата на матрицата користејќи `np.cov(data, rowvar=False)`.

Најди ги потоа сопствените вредности и сопствените вектори за коваријансната матрица.

Искористи го најголемиот сопствен вектор (кој се однесува на најголемата сопствена вредност) и направете проекција на точките врз тој вектор.
Проекцијата ја правите со матрично множење на точките со сопствениот вектор.

Бонус: Направете визуелизација на оригиналните точки, правата на која лежи сопствениот вектор, и точките по трансформација.

In [ ]:
P = np.array([[0, 1], [2, 3], [4, 5], [0, 6]])
cov = np.cov(P, rowvar=False)
print(cov, end='\n\n')
eigenvalues, eigenvectors = np.linalg.eig(cov)

print(eigenvalues, end='\n\n')
print(eigenvectors, end='\n\n')

max_vector = eigenvectors[:, 1]
max_value = np.max(eigenvalues)
print(max_value)
print(max_vector)

proekcija = P @ max_vector
print('\n', proekcija)

import matplotlib.pyplot as plt

plt.figure(figsize=(8, 8))
plt.scatter(P[:, 0], P[:, 1])
# plt.plot(P[:,0],P[:,1])
origin = np.mean(P, axis=0)  # Центрирање околу средиштето
plt.quiver(*origin, *max_vector, color='red', scale=3, label='Главен сопствен вектор')

for i, proj in enumerate(proekcija):
    proj_point = proj * max_vector + origin
    plt.plot([P[i, 0], proj_point[0]], [P[i, 1], proj_point[1]], 'k--')
    plt.scatter(*proj_point, color='green')  
